config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :dashboard, only: [:index]
  resources :student

  root 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/family.rb
class Family < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  extend FriendlyId

  friendly_id :nama_lengkap, use: :slugged

  belongs_to :dashboard, counter_cache: true

  counter_cache_with_conditions :dashboard, :jumlah_siswa_tk, [:jenis_kelamin, :jenjang_pendidikan], lambda{|jenis_kelamin, jenjang_pendidikan| jenis_kelamin == 1 && jenjang_pendidikan == 0} 

  counter_cache_with_conditions :dashboard, :jumlah_siswi_tk, [:jenis_kelamin, :jenjang_pendidikan], lambda{|jenis_kelamin, jenjang_pendidikan| jenis_kelamin == 2 && jenjang_pendidikan == 0} 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @kindergarten_students_count = Dashboard.first
  end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:search]
      @students = Student.where('nama_lengkap like ?', "%#{params[:search]}%").paginate(per_page: 5, page: params[:page])
    else
      @students = Student.order(nama_lengkap: :asc).paginate(per_page: 5, page: params[:page])
    end
  end

  def show
    @student = Student.friendly.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
    @student = Student.friendly.find(params[:id])

    if @student.destroy
      redirect_to student_index_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/dashboard/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h3 class="font-weight-bold">TKIT</h3>
  </div>
  <div class="col-md-2 text-center">
    <div class="card border-primary" style="max-width: 18rem;">
      <div class="card-header bg-primary"><h7 class="text-light font-weight-bold">SISWA</h7></div>
      <div class="card-body text-primary">
        <h3 class="card-title font-weight-bold">
          <font size="50"><%= @kindergarten_students_count.kindergarten_boys_student_count %></font> Org
        </h3>
      </div>
    </div>
  </div>
  <div class="col-md-2 text-center">
    <div class="card border-warning" style="max-width: 18rem;">
      <div class="card-header bg-warning"><h7 class="text-light font-weight-bold">SISWI</h7></div>
      <div class="card-body text-warning">
        <h3 class="card-title font-weight-bold">
          <font size="50"><%= @kindergarten_students_count.kindergarten_girls_student_count %></font> Org
        </h3>
      </div>
    </div>
  </div>
  <div class="col-md-2 text-center">
    <div class="card border-success" style="max-width: 18rem;">
      <div class="card-header bg-success"><h7 class="text-light font-weight-bold">TOTAL SISWA / I</h7></div>
      <div class="card-body text-success">
        <h3 class="card-title font-weight-bold">
          <font size="50"><%= @kindergarten_students_count.kindergarten_students_count %></font> Org
        </h3>
      </div>
    </div>
  </div>
</div>

app/views/kindergarten_student/index.html.erb
<div class="row">
  <div class="col-md-12" style="margin-bottom: 20px;"><h4 class="font-weight-bold">DAFTAR BIODATA SISWA / SISWI TKIT AN-NAHL</h4></div>
  <div class="col-md-9">
    <%= link_to 'Tambah', new_kindergarten_student_path, class: 'btn btn-primary' %>
  </div>
  <div class="col-md-3">
    <%= form_tag kindergarten_student_index_path, method: :get do %>
      <div class="input-group">
        <%= text_field_tag :search, nil, class: 'form-control', placeholder: 'Cari nama' %>
        <div class="input-group-append">
          <%= image_submit_tag('icons/search.svg', class: 'btn btn-primary') %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-12">
    <table class="table table-bordered">
      <thead align="center">
        <tr>
          <th>NISN</th>
          <th>NAMA LENGKAP</th>
          <th>JENIS KELAMIN</th>
          <th>TEMPAT LAHIR</th>
          <th>TANGGAL LAHIR</th>
          <th width=350>ALAMAT</th>
          <th>AKSI</th>
        </tr>
      </thead>
      <tbody>
        <% @kindergarten_students.each do |s| %>
          <tr>
              <td><%= s.nisn %></td>
              <td><%= s.fullname %></td>
              <td>
                <% if s.gender == 1 %>
                  Laki-laki
                <% else %>
                  Perempuan
                <% end %>
              </td>
              <td><%= s.place_of_birth %></td>
              <td><%= I18n.l(s.date_of_birth) %></td>
              <td><%= s.address %></td>
              <td>
                <%= link_to image_tag("icons/show.svg", class: 'icon-aksi'), kindergarten_student_path(s), title: 'Lihat' %>
                <%= link_to image_tag("icons/edit.svg", class: 'icon-aksi'), edit_kindergarten_student_path(s), title: 'Ubah' %>
                <%= link_to image_tag("icons/delete.svg", class: 'icon-aksi'), kindergarten_student_path(s), method: :delete, data: {confirm: 'Apakah anda yakin?'}, title: 'Hapus' %> 
              </td>
          </tr>
          <% end %>
      </tbody>
    </table>

    <%= will_paginate @kindergarten_students, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>

app/views/kindergarten_student/show.html.erb
<div class="row" style="font-size: 11pt;">
  <div class="col-md-12"><h4 class="font-weight-bold">BIODATA SISWA / SISWI TKIT AN-NAHL</h4></div>
  <div class="col-md-2" style="margin-top: 10px;">
    NISN
  </div>
  <div class="col-md-9" style="margin-top: 10px;">
    : <span class="bio"><%= @kindergarten_student.nisn %></span>
  </div>
  
  <div class="col-md-2" style="margin-top: 10px;" style="margin-top: 10px;">
    Nama Lengkap
  </div>
  <div class="col-md-9" style="margin-top: 10px;" style="margin-top: 10px;">
    : <span class="bio"><%= @kindergarten_student.fullname %></span>
  </div>

  <div class="col-md-2" style="margin-top: 10px;">
    Jenis Kelamin
  </div>
  <div class="col-md-9" style="margin-top: 10px;">
    : <span class="bio"><% if @kindergarten_student.gender == 1 %>Laki-laki<% else %>Perempuan<% end %></span>
  </div>

  <div class="col-md-2" style="margin-top: 10px;">
    Tempat Lahir
  </div>
  <div class="col-md-9" style="margin-top: 10px;">
    : <span class="bio"><%= @kindergarten_student.place_of_birth %></span>
  </div>
  
  <div class="col-md-2" style="margin-top: 10px;">
    Tanggal Lahir
  </div>
  <div class="col-md-9" style="margin-top: 10px;">
    : <span class="bio"><%= I18n.l(@kindergarten_student.date_of_birth) %></span>
  </div>

  <div class="col-md-2" style="margin-top: 10px;">
    Alamat
  </div>
  <div class="col-md-9" style="margin-top: 10px;">
    : <span class="bio"><%= @kindergarten_student.address %></span>
  </div>
  <div class="col-md-9" style="margin-top: 20px;">
    <%= link_to 'Kembali', kindergarten_student_index_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/layouts/_footer.html.erb
</main>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-expand-md navbar-dark bg-danger fixed-top">
    <a class="navbar-brand" href="#">S I S I T</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <% if controller.controller_name == 'dashboard' %>active<% end %>">
          <%= link_to 'Dashboard', dashboard_index_path, class: 'nav-link text-white' %>
        </li>
        <li class="nav-item <% if controller.controller_name == 'kindergarten_student' %>active<% end %>">
          <div class="dropdown show">
            <%= link_to 'Students', '#', class: 'nav-link dropdown-toggle', id: 'dropdownMenuLink', data: {toggle: 'dropdown'}, aria: {haspopup: 'true'}, aria: {expanded: 'false'} %>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <%= link_to 'TKIT', kindergarten_student_index_path, class: 'dropdown-item' %>
              <%= link_to 'SDIT', kindergarten_student_index_path, class: 'dropdown-item' %>
            </div>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
          <span class="nav-link text-white">Hi, <%= current_user.name.titleize %></span>
        </li>
        <li class="nav-item">
          <%= link_to 'Log out',  destroy_user_session_path, method: :delete, class: 'nav-link text-white' %>
        </li>
      </ul>
    </div>
  </nav>
<% end %>

<main role="main" class="container">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SISIT | Sistem Informasi Sekolah Islam Terpadu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>